### ISSUE TITLE
Proof corrections

### ISSUE THREAD

**Issue by CFGrote** [mpievolbio-scicomp/cancer_sim#27]
Addresses https://github.com/openjournals/joss-reviews/issues/2436#issuecomment-694118587

## TODOs:
- [x] Jake middle name inital
- [x] Check english spelling (UK)
- [x] Read and correct typos and misspellings
- [x] Check references
- [x] Check links

**Comment by CFGrote** [comment]
Done (PR #28)
